### ISSUE TITLE
add keybord shortcut

### ISSUE THREAD

**Issue by xela-zone** [fczbkk/Mouse-Pointer-Double#1]
[documentation for this feature](https://developer.chrome.com/extensions/commands)

it would be useful for already being in full screen and re-enabling the cursor.

**Comment by fczbkk** [comment]
Thanks for the suggestion. I just released a new version that supports keyboard shortcut.

It is `Alt+Shift+M` by default. You can edit it at [chrome://extensions/configureCommands](chrome://extensions/configureCommands).
